name: Tensorflow-GPU-V2.0
on: push

jobs:
  build:
    name: Tensorflow-GPU
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Docker
        env:
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
        run: |
          docker version
          echo $password | sudo docker login "registry.cn-hangzhou.aliyuncs.com" -u "$username" --password-stdin
      - name: Build Dockerfile
        env:
          version: 2.0
        run: |
          sudo docker build -f ./tensorflow/gpu/Dockerfile \
          --build-arg TF_PACKAGE_VERSION=$version \
          -t registry.cn-hangzhou.aliyuncs.com/njupt-isl/tensorflow-gpu:$version .
      - name: Push Dockerfile
        env:
          version: 2.0
        run: |
          sudo docker push registry.cn-hangzhou.aliyuncs.com/njupt-isl/tensorflow-gpu:$version