name: Tensorflow-CPU
on: push

jobs:
  build:
    - name: Tensorflow-CPU-V2.0
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Check Docker
          env:
            username: ${{ secrets.username }}
            password: ${{ secrets.password }}
          run: |
            docker version
            echo $password | sudo docker login "registry.cn-hangzhou.aliyuncs.com" -u "$username" --password-stdin
        - name: Build Dockerfile
          env:
            version: 2.0
          run: |
            sudo docker build -f ./tensorflow/gpu/Dockerfile \
            --build-arg TF_PACKAGE_VERSION=$version \
            -t registry.cn-hangzhou.aliyuncs.com/njupt-isl/tensorflow-cpu:$version .
        - name: Push Dockerfile
          env:
            version: 2.0
          run: |
            sudo docker push registry.cn-hangzhou.aliyuncs.com/njupt-isl/tensorflow-cpu:$version

    - name: Tensorflow-CPU-V1.15
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Check Docker
          env:
            username: ${{ secrets.username }}
            password: ${{ secrets.password }}
          run: |
            docker version
            echo $password | sudo docker login "registry.cn-hangzhou.aliyuncs.com" -u "$username" --password-stdin
        - name: Build Dockerfile
          env:
            version: 1.15
          run: |
            sudo docker build -f ./tensorflow/gpu/Dockerfile \
            --build-arg TF_PACKAGE_VERSION=$version \
            -t registry.cn-hangzhou.aliyuncs.com/njupt-isl/tensorflow-cpu:$version .
        - name: Push Dockerfile
          env:
            version: 1.15
          run: |
            sudo docker push registry.cn-hangzhou.aliyuncs.com/njupt-isl/tensorflow-cpu:$version

